name: AutoHotKey
on:
  push:
    paths:
      - 'windows/autohotkey/**'
jobs:
  compile:
    name: Compile MacWin AHK script
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install AutoHotKey
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install autohotkey-compiler
      - name: Compile hotkeys
        shell: cmd
        run: |
          RefreshEnv
          Ahk2Exe.exe /in windows\autohotkey\MacWinLayout.ahk /out MacWinLayout.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: MacWinLayout.exe
