name: Windows
on:
  push:
    paths:
      - 'windows/wsl/**'
      - '.github/workflows/windows.yml'
jobs:
  wsl:
    name: Enable WSL
    runs-on: windows-latest
    steps:
      - name: Enable WSL
        run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
        shell: powershell
      - name: Download Alpine rootfs
        run: powershell -File .\windows\wsl\Install.ps1 alpine
        shell: powershell
      - name: Install Alpine
        run: .\windows\wsl\alpine\alpine.exe
      - name: Check Alpine version
        run: .\windows\wsl\alpine\alpine.exe run -- cat /etc/os-release
