name: Windows
on:
  push:
    paths:
      - 'windows/wsl/**'
      - '.github/workflows/windows.yml'
defaults:
  run:
    working-directory: .\windows\wsl
    shell: powershell
jobs:
  wsl:
    name: WSL
    runs-on: windows-latest
    strategy:
      matrix:
        os: [alpine, ubuntu, debian]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Enable WSL
        run: Dism /online /Enable-Feature /FeatureName:Microsoft-Windows-Subsystem-Linux /All
      - name: Enable SMB
        run: Dism /online /Enable-Feature /FeatureName:SMB1Protocol /All
      - name: Download OS rootfs
        run: .\Install.ps1 ${{ matrix.os }}
      - name: Install OS
        run: .\${{ matrix.os }}\${{ matrix.os }}.exe
      - name: Check OS version
        run: .\${{ matrix.os }}\${{ matrix.os }}.exe run -- cat /etc/os-release
