name: Windows
on:
  push:
    paths:
      - 'windows/wsl/**'
jobs:
  wsl:
    name: Enable WSL
    runs-on: windows-latest
    steps:
      - name: Enable WSL
        run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
        shell: powershell
      - name: Download Alpine rootfs
        run: & ".\windows\wsl\Install.ps1" alpine
        shell: powershell
      - name: Install Alpine
        shell: powershell
        run: .\windows\wsl\alpine\alpine.exe
      - name: Check Alpine version
        shell: powershell
        run: .\windows\wsl\alpine\alpine.exe run -- cat /etc/os-release
