name: Prepare WSL distributions
on: push
jobs:
  debian:
    runs-on: windows-latest
    steps:
      - name: Install WSL
        shell: powershell
        run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
      - name: Download Linux distribution
        shell: powershell
        run: Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu -OutFile Ubuntu.appx -UseBasicParsing
      - name: Install WSL
        shell: powershell
        run: |
          Rename-Item .\Ubuntu.appx .\Ubuntu.zip
          Expand-Archive .\Ubuntu.zip .\Ubuntu
          $userenv = [System.Environment]::GetEnvironmentVariable("Path", "User")
          [System.Environment]::SetEnvironmentVariable("PATH", $userenv + ";C:\Users\Administrator\Ubuntu", "User")
      - name: Launch WSL
        shell: powershell
        run: Ubuntu.exe
